version: '2'

volumes:
  data-volume:
  perfectpay-laravel-mysql-data:
    driver: local

services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: perfectpay-laravel-mysql
    volumes:
      - perfectpay-laravel-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=perfectpay-laravel
      - MYSQL_DATABASE=perfectpay-laravel
      - MYSQL_USER=perfectpay-laravel
      - MYSQL_PASSWORD=perfectpay-laravel
  app:
    image: ambientum/php:8.1-nginx
    container_name: perfectpay-laravel-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
